### ISSUE TITLE
闪退问题

### ISSUE THREAD

**Issue by Deep20160607** [suming77/SumTea_Android#2]
点击短视频闪退: `java.lang.AbstractMethodError: abstract method "void com.google.android.exoplayer2.Player$Listener.onSurfaceSizeChanged(int, int)"
                                                                                                    	at com.google.android.exoplayer2.ExoPlayerImpl.lambda$maybeNotifySurfaceSizeChanged$27(ExoPlayerImpl.java:2596)
                                                                                                    	at com.google.android.exoplayer2.ExoPlayerImpl$$ExternalSyntheticLambda23.invoke(Unknown Source:6)
                                                                                                    	at com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.invoke(ListenerSet.java:330)
                                                                                                    	at com.google.android.exoplayer2.util.ListenerSet.lambda$queueEvent$0(ListenerSet.java:214)
                                                                                                    	at com.google.android.exoplayer2.util.ListenerSet$$ExternalSyntheticLambda1.run(Unknown Source:6)
                                                                                                    	at com.google.android.exoplayer2.util.ListenerSet.flushEvents(ListenerSet.java:236)
                                                                                                    	at com.google.android.exoplayer2.util.ListenerSet.sendEvent(ListenerSet.java:251)
                                                                                                    	at com.google.android.exoplayer2.ExoPlayerImpl.maybeNotifySurfaceSizeChanged(ExoPlayerImpl.java:2595)
                                                                                                    	at com.google.android.exoplayer2.ExoPlayerImpl.access$1800(ExoPlayerImpl.java:109)
                                                                                                    	at com.google.android.exoplayer2.ExoPlayerImpl$ComponentListener.surfaceChanged(ExoPlayerImpl.java:2953)
                                                                                                    	at android.view.SurfaceView.updateSurface(SurfaceView.java:916)
                                                                                                    	at android.view.SurfaceView$2.onPreDraw(SurfaceView.java:180)
                                                                                                    	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1088)
                                                                                                    	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3248)
                                                                                                    	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2121)
                                                                                                    	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8554)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1073)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:897)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:824)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1058)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:883)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                                    	at android.os.Looper.loop(Looper.java:238)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7823)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:532)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
2023-05-16 17:10:01.999  1486-2247  OppoThermalStats        system_server                        E  Error getting package info: com.oppo.launcher
2023-05-16 17:10:02.045  1486-1756  InputDispatcher         system_server                        E  channel '7ea2186 com.sum.tea/com.sum.video.VideoPlayActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2023-05-16 17:10:02.045  1486-1756  InputDispatcher         system_server                        E  channel '3b301c8 com.sum.tea/com.sum.video.VideoPlayActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2023-05-16 17:10:02.045  1486-1756  InputDispatcher         system_server                        E  channel 'bee977c com.sum.tea/com.sum.main.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2023-05-16 17:10:02.070 21331-21352 SafeCenter...ityMonitor com.coloros.persist.system           E  onProcessDied com.sum.tea`

**Comment by Deep20160607** [comment]
通过:
android.enableDexingArtifactTransform.desugaring=false和在app下proguard-rules.pro中加入混淆 -keep class org.webrtc.** { *; } 
可以解决
